const buttonsData = [
  [
    {
      code: 'Backquote',
      enKey: '`',
      ruKey: 'Ё',
      enKeyShift: '~',
    },
    {
      code: 'Digit1',
      enKey: '1',
      ruKey: '1',
      enKeyShift: '!',
      ruKeyShift: '!',
    },
    {
      code: 'Digit2',
      enKey: '2',
      ruKey: '2',
      enKeyShift: '@',
      ruKeyShift: '"',
    },
    {
      code: 'Digit3',
      enKey: '3',
      ruKey: '3',
      enKeyShift: '#',
      ruKeyShift: '№',
    },
    {
      code: 'Digit4',
      enKey: '4',
      ruKey: '4',
      enKeyShift: '$',
      ruKeyShift: ';',
    },
    {
      code: 'Digit5',
      enKey: '5',
      ruKey: '5',
      enKeyShift: '%',
      ruKeyShift: '%',
    },
    {
      code: 'Digit6',
      enKey: '6',
      ruKey: '6',
      enKeyShift: '^',
      ruKeyShift: ':',
    },
    {
      code: 'Digit7',
      enKey: '7',
      ruKey: '7',
      enKeyShift: '&',
      ruKeyShift: '?',
    },
    {
      code: 'Digit8',
      enKey: '8',
      ruKey: '8',
      enKeyShift: '*',
      ruKeyShift: '*',
    },
    {
      code: 'Digit9',
      enKey: '9',
      ruKey: '9',
      enKeyShift: '(',
      ruKeyShift: '(',
    },
    {
      code: 'Digit0',
      enKey: '0',
      ruKey: '0',
      enKeyShift: ')',
      ruKeyShift: ')',
    },
    {
      code: 'Minus',
      enKey: '-',
      ruKey: '-',
      enKeyShift: '_',
      ruKeyShift: '_',
    },
    {
      code: 'Equal',
      enKey: '=',
      ruKey: '=',
      enKeyShift: '+',
      ruKeyShift: '+',
    },
    {
      code: 'Backspace',
      enKey: 'backspace',
      ruKey: 'backspace',
      enKeyShift: 'backspace',
      ruKeyShift: 'backspace',
      type: { size: '_type_duble', color: true },
    },
  ],
  [
    {
      code: 'Tab',
      enKey: 'tab',
      ruKey: 'tab',
      enKeyShift: 'tab',
      ruKeyShift: 'tab',
      type: { size: false, color: true },
    },
    {
      code: 'KeyQ',
      enKey: 'Q',
      ruKey: 'Й',
    },
    {
      code: 'KeyW',
      enKey: 'W',
      ruKey: 'Ц',
    },
    {
      code: 'KeyE',
      enKey: 'E',
      ruKey: 'У',
    },
    {
      code: 'KeyR',
      enKey: 'R',
      ruKey: 'К',
    },
    {
      code: 'KeyT',
      enKey: 'T',
      ruKey: 'Е',
    },
    {
      code: 'KeyY',
      enKey: 'Y',
      ruKey: 'Н',
    },
    {
      code: 'KeyU',
      enKey: 'U',
      ruKey: 'Г',
    },
    {
      code: 'KeyI',
      enKey: 'I',
      ruKey: 'Ш',
    },
    {
      code: 'KeyO',
      enKey: 'O',
      ruKey: 'Щ',
    },
    {
      code: 'KeyP',
      enKey: 'P',
      ruKey: 'З',
    },
    {
      code: 'BracketLeft',
      enKey: '[',
      ruKey: 'Х',
      enKeyShift: '{',
    },
    {
      code: 'BracketRight',
      enKey: ']',
      ruKey: 'Ъ',
      enKeyShift: '}',
    },
    {
      code: 'Backslash',
      enKey: '\\',
      ruKey: '\\',
      enKeyShift: '|',
      ruKeyShift: '/',
    },
    {
      code: 'Delete',
      enKey: 'del',
      ruKey: 'del',
      enKeyShift: 'del',
      ruKeyShift: 'del',
      type: { size: false, color: true },
    },
  ],
  [
    {
      code: 'CapsLock',
      enKey: 'capslock',
      ruKey: 'capslock',
      enKeyShift: 'capslock',
      ruKeyShift: 'capslock',
      type: { size: '_type_duble', color: true },
    },
    {
      code: 'KeyA',
      enKey: 'A',
      ruKey: 'Ф',
    },
    {
      code: 'KeyS',
      enKey: 'S',
      ruKey: 'Ы',
    },
    {
      code: 'KeyD',
      enKey: 'D',
      ruKey: 'В',
    },
    {
      code: 'KeyF',
      enKey: 'F',
      ruKey: 'А',
    },
    {
      code: 'KeyG',
      enKey: 'G',
      ruKey: 'П',
    },
    {
      code: 'KeyH',
      enKey: 'H',
      ruKey: 'Р',
    },
    {
      code: 'KeyJ',
      enKey: 'J',
      ruKey: 'О',
    },
    {
      code: 'KeyK',
      enKey: 'K',
      ruKey: 'Л',
    },
    {
      code: 'KeyL',
      enKey: 'L',
      ruKey: 'Д',
    },
    {
      code: 'Semicolon',
      enKey: ';',
      ruKey: 'Ж',
      enKeyShift: ':',
    },
    {
      code: 'Quote',
      enKey: "'",
      ruKey: 'Э',
      enKeyShift: '"',
    },
    {
      code: 'Enter',
      enKey: 'enter',
      ruKey: 'enter',
      type: { size: '_type_duble', color: true },
    },
  ],
  [
    {
      code: 'ShiftLeft',
      enKey: 'shift',
      ruKey: 'shift',
      enKeyShift: 'shift',
      ruKeyShift: 'shift',
      type: { size: '_type_duble', color: true },
    },
    {
      code: 'KeyZ',
      enKey: 'Z',
      ruKey: 'Я',
    },
    {
      code: 'KeyX',
      enKey: 'X',
      ruKey: 'Ч',
    },
    {
      code: 'KeyC',
      enKey: 'C',
      ruKey: 'С',
    },
    {
      code: 'KeyV',
      enKey: 'V',
      ruKey: 'М',
    },
    {
      code: 'KeyB',
      enKey: 'B',
      ruKey: 'И',
    },
    {
      code: 'KeyN',
      enKey: 'N',
      ruKey: 'Т',
    },
    {
      code: 'KeyM',
      enKey: 'M',
      ruKey: 'Ь',
    },
    {
      code: 'Comma',
      enKey: ',',
      ruKey: 'Б',
      enKeyShift: '<',
    },
    {
      code: 'Period',
      enKey: '.',
      ruKey: 'Ю',
      enKeyShift: '>',
    },
    {
      code: 'Slash',
      enKey: '/',
      ruKey: '.',
      enKeyShift: '?',
      ruKeyShift: ',',
    },
    {
      code: 'ArrowUp',
      enKey: '▲',
      ruKey: '▲',
      enKeyShift: '▲',
      ruKeyShift: '▲',
      type: { size: false, color: true },
    },
    {
      code: 'ShiftRight',
      enKey: 'shift',
      ruKey: 'shift',
      enKeyShift: 'shift',
      ruKeyShift: 'shift',
      type: { size: '_type_duble', color: true },
    },
  ],
  [
    {
      code: 'ControlLeft',
      enKey: 'ctrl',
      ruKey: 'ctrl',
      enKeyShift: 'ctrl',
      ruKeyShift: 'ctrl',
      type: { size: false, color: true },
    },
    {
      code: 'MetaLeft',
      enKey: 'win',
      ruKey: 'win',
      type: { size: false, color: true },
    },
    {
      code: 'AltLeft',
      enKey: 'alt',
      ruKey: 'alt',
      type: { size: false, color: true },
    },
    {
      code: 'Space',
      enKey: ' ',
      ruKey: ' ',
      enKeyShift: ' ',
      ruKeyShift: ' ',
      type: { size: '_type_max', color: true },
    },
    {
      code: 'AltRight',
      enKey: 'alt',
      ruKey: 'alt',
      type: { size: '_type_duble', color: true },
    },
    {
      code: 'ArrowLeft',
      enKey: '◄',
      ruKey: '◄',
      enKeyShift: '◄',
      ruKeyShift: '◄',
      type: { size: false, color: true },
    },
    {
      code: 'ArrowDown',
      enKey: '▼',
      ruKey: '▼',
      enKeyShift: '▼',
      ruKeyShift: '▼',
      type: { size: false, color: true },
    },
    {
      code: 'ArrowRight',
      enKey: '►',
      ruKey: '►',
      enKeyShift: '►',
      ruKeyShift: '►',
      type: { size: false, color: true },
    },
    {
      code: 'ControlRight',
      enKey: 'ctrl',
      ruKey: 'ctrl',
      type: { size: false, color: true },
    },
  ],
];

export default buttonsData;
